resources:
  - name: helpq
    type: git
    source:
      uri: https://github.com/HackGT/HELPq.git
      branch: dev

  - name: helpq-image
    type: docker-image
    source:
      repository: hackgt/helpq
      email: {{dockerhub_email}}
      username: {{dockerhub_user}}
      password: {{dockerhub_pass}}

jobs:
  - name: build-helpq
    plan:
      - get: helpq
        trigger: true
      - put: helpq-image
        params:
          build: helpq
