resources:
  - name: helpq
    type: git
    source:
      uri: https://github.com/HackGT/HELPq.git
      branch: dev

  - name: helpq-image
    type: docker-image
    source:
      repository: hackgt/helpq
      username: lol
      password: trololo

jobs:
  - name: build-helpq
    plan:
      - get: helpq
        trigger: true
      - put: helpq-image
        params:
          build: helpq
        get_params:
          save: true
      - task: build-test
        file: helpq/build.yml
